services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@365
    volumes:
      - ./postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - docker-compose-stack-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin@365
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5431:80"
    depends_on:
      - postgres
    networks:
      - docker-compose-stack-network

networks:
  docker-compose-stack-network:
    external: true
